/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Task info dep
    // id("org.barfuin.gradle.taskinfo") version "1.2.5" // Use the latest version

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.AppKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// Example of registering a custom task...
/*
macbookpro:gradle-tutorial mkwyche$ ./gradlew :app:copyTask
Calculating task graph as no cached configuration is available for tasks: :app:copyTask

BUILD SUCCESSFUL in 1s
Configuration cache entry stored.
 */
tasks.register<Copy>("copyTask") {
    from("source")
    into("target")
    include("*.war")
}

// Understanding Dependencies Between Tasks
/*
macbookpro:gradle-tutorial mkwyche$ ./gradlew :app:greet
Calculating task graph as no cached configuration is available for tasks: :app:greet

> Task :app:hello
Hello!

> Task :app:greet
How are you?

BUILD SUCCESSFUL in 1s
2 actionable tasks: 2 executed
 */
tasks.register("hello") {
    doLast {
        println("Hello!")
    }
}

tasks.register("greet") {
    doLast {
        println("How are you?")
    }
    dependsOn("hello")
}